# Generated by Django 3.1.7 on 2021-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='non exist', max_length=100),
            preserve_default=False,
        ),
    ]
