# Generated by Django 3.1.7 on 2021-02-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
    ]
