# Generated by Django 3.1.7 on 2021-03-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yierra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=24)),
                ('vehicle_speed', models.IntegerField()),
                ('hybrid_battery_pack_remaining_life', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ELM_VERSION', models.CharField(max_length=50)),
                ('ELM_VOLTAGE', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yierra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yierra')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_load', models.IntegerField()),
                ('engine_coolant_temperature', models.IntegerField()),
                ('fuel_pressure', models.IntegerField()),
                ('engine_rpm', models.IntegerField()),
                ('timing_advance', models.IntegerField()),
                ('intake_air_temp', models.IntegerField()),
                ('air_flow_rate', models.IntegerField()),
                ('throttle_position', models.IntegerField()),
                ('engine_run_time', models.IntegerField()),
                ('fuel_level_input', models.IntegerField()),
                ('warmups_since_codes_cleared', models.IntegerField()),
                ('barometric_pressure', models.IntegerField()),
                ('ambient_air_temperature', models.IntegerField()),
                ('commanded_throttle_actuator', models.IntegerField()),
                ('time_run_with_MIL_on', models.IntegerField()),
                ('time_since_trouble_codes_cleared', models.IntegerField()),
                ('engine_fuel_rate', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
    ]
